index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'create.html.twig'

redirect:
    path: /link/{identifier}
    controller: App\Controller\RedirectController::redirectTo
    requirements:
        identifier: '[A-Za-z0-9]{1,10}'
    methods: GET

encode_route:
    path: /api/encode
    controller: App\Controller\ShortenerController::encode
    methods: POST
