parameters:
    google_safe_browsing_api_key: '%env(GOOGLE_SAFE_BROWSING_API_KEY)%'
    google_safe_browsing_client_id: 'URL Shortener test task'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Services\Link\Converter:
        arguments:
            $baseUrl: '%env(SHORTENER_BASE_URL)%'
    App\Services\Link\EncoderInterface: '@App\Services\Link\Converter'
    App\Services\Link\DecoderInterface: '@App\Services\Link\Converter'

    App\Services\Link\RepositoryInterface: '@App\Repository\ShortLinkRepository'

    App\Services\SafeBrowsing\Client:
        arguments:
            $apiKey: '%google_safe_browsing_api_key%'
            $clientId: '%google_safe_browsing_client_id%'

    Psr\Http\Client\ClientInterface: '@App\Services\PSR\Http\Client\Adapter\Guzzle'

    App\Services\PSR\Http\Client\Adapter\Guzzle:
        arguments:
            $guzzle: '@GuzzleHttp\Client'

    GuzzleHttp\Client:
        arguments:
            $config:
                timeout: 5
                connect_timeout: 5
